// file name: what_are_custom_inputs.c
// user name: xmsfgp
// problem lvl: easy
// created at: 2024-01-20 19:20:22

/*
    What are custom inputs?
    You will usually find a custom inputs box in programming problems.
    Custom inputs allow you to do the following

    You are able to see the output generated by your code for inputs defined by you
    Test your code with your sample inputs.
    This helps you debug Wrong Answers (WA), Runtime Errors (RE) faster
    Create your own test cases.
    In programming problems - you want to find exceptions or test cases where your code / logic can fail.
    Custom inputs allow you to test your code for the same.
*/